### ISSUE TITLE
使用していないモジュールのインポート

### ISSUE THREAD

**Issue by takanory** [Posbin/DjangoExam#3]
## 目的

* 使用していないモジュールをimportしているので削除する
* https://github.com/Posbin/DjangoExam/blob/master/FruitSalesMgmt/views.py#L1
* flake8 を使うと指摘されるはず

**Comment by posbin** [comment]
下記コミットでviews.pyの2行目を修正しました。
https://github.com/Posbin/DjangoExam/commit/f51c9bdac3726e9f67eb6e2326fd5fc92b565b07

**Comment by takanory** [comment]
OKです
